version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - socialMediaManagerNetwork
    depends_on:
      - gateway
      - ui

  messageBroker:
    image: rabbitmq
    depends_on:
      - gateway
    container_name: messageBroker
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - socialMediaManagerNetwork

  gateway:
    build: ./services/gateway
    volumes:
      - ./services/gateway:/services/gateway
    networks:
      - socialMediaManagerNetwork
    depends_on:
      - twitter

  twitter:
    build: ./services/twitter
    volumes:
      - ./services/twitter:/services/twitter
    networks:
      - socialMediaManagerNetwork

  ui:
    build: ./ui
    volumes:
      - ./ui:/app/ui
    networks:
      - socialMediaManagerNetwork
    depends_on:
      - gateway

networks:
  socialMediaManagerNetwork:
    driver: bridge